"""added an upvote column

Revision ID: 028c180d56fd
Revises: 5336b49292d2
Create Date: 2020-01-18 20:26:06.257268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028c180d56fd'
down_revision = '5336b49292d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.add_column('comments', sa.Column('downvote', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('upvote', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'upvote')
    op.drop_column('comments', 'downvote')
    op.drop_column('comments', 'disabled')
    # ### end Alembic commands ###
