"""added column last edited to posts table

Revision ID: 3720cfdbf113
Revises: 097ca5609a4d
Create Date: 2020-01-14 13:00:52.875928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3720cfdbf113'
down_revision = '097ca5609a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('last_edited', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'last_edited')
    # ### end Alembic commands ###
