"""added edited column

Revision ID: 39f9f2c2b2d3
Revises: 028c180d56fd
Create Date: 2020-01-18 21:12:08.541977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f9f2c2b2d3'
down_revision = '028c180d56fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('edited', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'edited')
    # ### end Alembic commands ###
