"""Added new association table FOLLOW and related columns and methods in USER

Revision ID: 56acd94da2c9
Revises: 26c248bb5f9c
Create Date: 2020-01-17 15:53:30.328000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56acd94da2c9'
down_revision = '26c248bb5f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
