"""added a new column to posts 'html_body'

Revision ID: 94820df46346
Revises: 3720cfdbf113
Create Date: 2020-01-16 20:52:43.080470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94820df46346'
down_revision = '3720cfdbf113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
