"""added a password field

Revision ID: c1f64326ab4c
Revises: 8d429b024b8d
Create Date: 2019-12-22 08:04:59.906534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f64326ab4c'
down_revision = '8d429b024b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_User__password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_User__password_hash')
    # ### end Alembic commands ###
